[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/pi/printer_data/comms/klippy.sock

[authorization]
force_logins: false
trusted_clients:
    127.0.0.1
    192.168.0.0/24
    100.64.0.0/10
    10.0.0.0/8
cors_domains:
    *.brandstaetter.rocks
    *.brandstaetter.nl
    *.lan
    *.local
    *://localhost
    *://localhost:*
    *://my.mainsail.xyz
    *://app.fluidd.xyz

[octoprint_compat]

[history]

[file_manager]
enable_object_processing: True

[update_manager]
channel: dev
refresh_interval: 168

[update_manager mainsail]
path: /home/pi/mainsail
repo: mainsail-crew/mainsail
channel: stable
type: web
persistent_files:
    config.json

[update_manager mainsail-config]
managed_services: klipper
origin: https://github.com/mainsail-crew/mainsail-config.git
path: /home/pi/mainsail-config
primary_branch: master
type: git_repo

# Crowsnest update_manager entry
[update_manager crowsnest]
type: git_repo
path: ~/crowsnest
origin: https://github.com/mainsail-crew/crowsnest.git
managed_services: crowsnest
install_script: tools/pkglist.sh

[include moonraker-obico-update.cfg]

[update_manager timelapse]
type: git_repo
primary_branch: main
path: ~/moonraker-timelapse
origin: https://github.com/mainsail-crew/moonraker-timelapse.git
managed_services: klipper moonraker

[timelapse]
output_path: ~/printer_data/timelapse/
frame_path: /tmp/timelapse/printer
ffmpeg_binary_path: /usr/bin/ffmpeg

[update_manager moonraker-obico]
type: git_repo
path: ~/moonraker-obico
origin: https://github.com/TheSpaghettiDetective/moonraker-obico.git
env: /home/pi/moonraker-env/bin/python
requirements: requirements.txt
install_script: install.sh
managed_services:
  moonraker-obico

[update_manager KAMP]
type: git_repo
channel: dev
path: ~/KAMP
origin: https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging.git
managed_services: klipper
primary_branch: main
